// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelefonRehberi.Models;

#nullable disable

namespace TelefonRehberi.Migrations
{
    [DbContext(typeof(TelefonRehberiContext))]
    partial class TelefonRehberiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TelefonRehberi.Models.TelefonRehberi", b =>
                {
                    b.Property<int>("RehberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RehberId"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("E_Mail")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Fax_Numarasi")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefon_Numarasi")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("RehberId");

                    b.ToTable("TelefonRehberleri");
                });
#pragma warning restore 612, 618
        }
    }
}
